name: 'AI Code Review with Claude'
description: 'Automated code review using Claude AI with custom review instructions from any text-based file'
author: 'Anthropic'

branding:
  icon: 'check-circle'
  color: 'orange'

inputs:
  anthropic-api-key:
    description: 'Anthropic API key for Claude access'
    required: true
  github-token:
    description: 'GitHub token for API access'
    required: true
    default: ${{ github.token }}
  rules-file:
    description: 'Path to the review instructions file in the repository (any text format: Markdown, YAML, plain text, etc.)'
    required: false
    default: '.github/copilot-instructions.md'
  github-repository:
    description: 'GitHub repository name'
    required: false
    default: ${{ github.repository }}
  github-pr-number:
    description: 'GitHub pull request number'
    required: false
    default: ${{ github.event.pull_request.number }}

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    ANTHROPIC_API_KEY: "${{ inputs.anthropic-api-key }}"
    GITHUB_TOKEN: "${{ inputs.github-token }}"
    GITHUB_REPOSITORY: "${{ inputs.github-repository }}"
    PR_NUMBER: "${{ inputs.github-pr-number }}"
    RULES_FILE: ${{ inputs.rules-file }}
